'use strict'
var _ = require('lodash')

class Deck {
  constructor () {
    this.deck = _.shuffle(getDeck())
  }

  /* PUBLIC * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

  getCards (count) {
    return _.pullAt(this.deck, _.range(count))
  }
}

module.exports = Deck

function getDeck () {
  return [
    { 'F0001': 'I gritted my teeth' },
    { 'F0002': 'Thank you for your help,' },
    { 'F0003': 'They saw something strange' },
    { 'F0004': 'Congratulations!' },
    { 'F0005': 'Thats unimportant' },
    { 'F0006': 'Today is March 5th.' },
    { 'F0007': 'School begins at 9.' },
    { 'F0008': 'This hat cost me $10.' },
    { 'F0009': 'The bill was $30.' },
    { 'F0010': 'Thatll be $30.' },
    { 'F0011': 'I owe you $30.' },
    { 'F0012': 'Did you say 30?' },
    { 'F0013': 'Ill give you $30.' },
    { 'F0014': 'I have $300.' },
    { 'F0015': 'Was Tom abandoned?' },
    { 'F0016': 'Tom was abducted.' },
    { 'F0017': 'Let Tom come aboard.' },
    { 'F0018': 'May I come aboard?' },
    { 'F0019': 'Im going aboard.' },
    { 'F0020': 'Is Tom still aboard?' },
    { 'F0021': 'Whats this all about?' },
    { 'F0023': 'What was that about?' },
    { 'F0024': 'Whats it all about?' },
    { 'F0025': 'Whats all this about?' },
    { 'F0026': 'Whats that all about?' },
    { 'F0027': 'Whats this book about?' },
    { 'F0028': 'What is this about?' },
    { 'F0029': 'Have you been abroad?' },
    { 'F0030': 'I study abroad.' },
    { 'F0031': 'She has gone abroad.' },
    { 'F0032': 'Tom stopped abruptly.' },
    { 'F0033': 'Tom was abusive.' },
    { 'F0034': 'Its acceptable.' },
    { 'F0035': 'Thats acceptable.' },
    { 'F0036': 'Im an accountant.' },
    { 'F0037': 'Is this accurate?' },
    { 'F0038': 'Is that accurate?' },
    { 'F0039': 'Does your head still ache?' },
    { 'F0040': 'My head really aches.' },
    { 'F0041': 'He was acquitted.' },
    { 'F0042': 'Tom was acquitted.' },
    { 'F0043': 'Its time for action.' },
    { 'F0044': 'Youre a good actor.' },
    { 'F0045': 'Is Tom an actor?' },
    { 'F0046': 'He is an actor.' },
    { 'F0047': 'Tom is an actor.' },
    { 'F0048': 'Tom was adamant.' },
    { 'F0049': 'Im adaptable.' },
    { 'F0050': 'Were adaptable.' },
    { 'F0051': 'Was Tom an addict?' },
    { 'F0052': 'They got addicted.' },
    { 'F0053': 'Tom was addicted.' },
    { 'F0054': 'He changed his address.' },
    { 'F0055': 'Ive got Toms address.' },
    { 'F0056': 'I have Toms address.' },
    { 'F0057': 'I need Toms address.' },
    { 'F0058': 'Give me Toms address.' },
    { 'F0059': 'Tell me your address.' },
    { 'F0060': 'What is your address?' },
    { 'F0061': 'Whats your home address?' },
    { 'F0062': 'It was adequate.' },
    { 'F0063': 'Is Tom adopted?' },
    { 'F0064': 'Tom was adopted.' },
    { 'F0065': 'You were adopted.' },
    { 'F0066': 'Its adorable.' },
    { 'F0067': 'Youre adorable.' },
    { 'F0068': 'Tom is an adult.' },
    { 'F0069': 'I paid in advance.' },
    { 'F0070': 'Its an adventure.' },
    { 'F0071': 'He likes adventure.' },
    { 'F0072': 'Im adventurous.' },
    { 'F0073': 'How adventurous!' },
    { 'F0074': 'Were adventurous.' },
    { 'F0075': 'Youre adventurous.' },
    { 'F0076': 'We dont advertise.' },
    { 'F0077': 'Please take my advice.' },
    { 'F0078': 'I need some advice.' },
    { 'F0079': 'We want your advice.' },
    { 'F0080': 'I took your advice.' },
    { 'F0081': 'Thanks for your advice.' },
    { 'F0082': 'Follow my advice.' },
    { 'F0083': 'I need your advice.' },
    { 'F0084': 'What do you advise?' },
    { 'F0085': 'What would you advise?' },
    { 'F0086': 'Ill keep you advised.' },
    { 'F0087': 'Arent you afraid?' },
    { 'F0088': 'I wont be afraid.' },
    { 'F0089': 'Please dont be afraid.' },
    { 'F0090': 'I know youre afraid.' },
    { 'F0091': 'I was too afraid.' },
    { 'F0092': 'Why are they afraid?' },
    { 'F0093': 'Are you still afraid?' },
    { 'F0094': 'Im very afraid.' },
    { 'F0095': 'I wasnt afraid.' },
    { 'F0096': 'Tom wasnt afraid.' },
    { 'F0097': 'What were they after?' },
    { 'F0098': 'Whatre you after?' },
    { 'F0099': 'What are you after?' },
    { 'F0100': 'What are they after?' },
    { 'F0101': 'Lets try once again.' },
    { 'F0102': 'Dont call me again.' },
    { 'F0103': 'Whats your name again?' },
    { 'F0104': 'Lets watch that again.' },
    { 'F0105': 'Lets try it again.' },
    { 'F0106': 'Dont do it again.' },
    { 'F0107': 'Tom chuckled again.' },
    { 'F0108': 'Tom giggled again.' },
    { 'F0109': 'Theyre coming again.' },
    { 'F0110': 'Im staring again.' },
    { 'F0111': 'Im working again.' },
    { 'F0112': 'It happened again.' },
    { 'F0113': 'Its happened again.' },
    { 'F0114': 'Its started again.' },
    { 'F0115': 'Its starting again.' },
    { 'F0116': 'Lets try Tom again.' },
    { 'F0117': 'Dont ask me again.' },
    { 'F0118': 'Dont leave me again.' },
    { 'F0119': 'Dont say it again.' },
    { 'F0120': 'Dont start that again.' },
    { 'F0121': 'Dont touch me again.' },
    { 'F0122': 'Dont try that again.' },
    { 'F0123': 'I wont ask again.' },
    { 'F0124': 'Tom has killed again.' },
    { 'F0125': 'We wont speak again.' },
    { 'F0126': 'We wont meet again.' },
    { 'F0127': 'Youre bleeding again.' },
    { 'F0128': 'Ill call you again.' },
    { 'F0129': 'Tom stood up again.' },
    { 'F0130': 'Tom sat down again.' },
    { 'F0131': 'Ill see you again.' },
    { 'F0132': 'Ill say it again.' },
    { 'F0133': 'Youll need this again.' },
    { 'F0134': 'We could start again.' },
    { 'F0135': 'Tom tricked us again.' },
    { 'F0136': 'Youre early again.' },
    { 'F0137': 'Who are you again?' },
    { 'F0138': 'We need you again.' },
    { 'F0139': 'Talk to Tom again.' },
    { 'F0140': 'Here we are again.' },
    { 'F0141': 'Tom did it again.' },
    { 'F0142': 'Look at it again.' },
    { 'F0143': 'Tom is drunk again.' },
    { 'F0144': 'Its that time again.' },
    { 'F0145': 'Let me try again.' },
    { 'F0146': 'We could try again.' },
    { 'F0147': 'Check Toms pulse again.' },
    { 'F0148': 'Can I start again?' },
    { 'F0149': 'You did it again.' },
    { 'F0150': 'I saw Tom again.' },
    { 'S0001': 'Lets begin on page 30.' },
    { 'S0002': 'Its 3:30.' },
    { 'S0003': 'I took Highway 58.' },
    { 'S0004': 'Tom retired at 65.' },
    { 'S0005': 'What are you concerned about?' },
    { 'S0006': 'What are you thinking about?' },
    { 'S0007': 'What is the letter about?' },
    { 'S0008': 'What is all the fuss about?' },
    { 'S0009': 'Whatre you talking about?' },
    { 'S0010': 'What were you dreaming about?' },
    { 'S0011': 'I had things to think about.' },
    { 'S0012': 'I dont know what its about.' },
    { 'S0013': 'What were you thinking about?' },
    { 'S0014': 'What are you angry about?' },
    { 'S0015': 'Whats Tom complaining about?' },
    { 'S0016': 'Whatre you thinking about?' },
    { 'S0017': 'What are you smirking about?' },
    { 'S0018': 'Whats Tom so happy about?' },
    { 'S0019': 'Whats Tom so angry about?' },
    { 'S0020': 'Whatre you taking about?' },
    { 'S0021': 'What are you laughing about?' },
    { 'S0022': 'What are you smiling about?' },
    { 'S0023': 'What was Tom talking about?' },
    { 'S0024': 'Whats there to worry about?' },
    { 'S0025': 'Who were they talking about?' },
    { 'S0026': 'What did you two talk about?' },
    { 'S0027': 'What are they talking about?' },
    { 'S0028': 'Theres plenty to talk about.' },
    { 'S0029': 'Theres so much to talk about.' },
    { 'S0030': 'Theres nothing to talk about.' },
    { 'S0031': 'Tell me what this is about.' },
    { 'S0032': 'What was I talking about?' },
    { 'S0033': 'I know what this is about.' },
    { 'S0034': 'What were we talking about?' },
    { 'S0035': 'What are you talking about?' },
    { 'S0036': 'Thats not what this is about.' },
    { 'S0037': 'Do you think Im abrasive?' },
    { 'S0038': 'Do you plan to go abroad?' },
    { 'S0039': 'Is this your first trip abroad?' },
    { 'S0040': 'I have never been abroad.' },
    { 'S0041': 'Have you ever been abroad?' },
    { 'S0042': 'I want to study abroad.' },
    { 'S0043': 'Is your uncle still abroad?' },
    { 'S0044': 'He just returned from abroad.' },
    { 'S0045': 'Half the students were absent.' },
    { 'S0046': 'Tom has a southern accent.' },
    { 'S0047': 'Tom has a British accent.' },
    { 'S0048': 'Dont you just love Toms accent?' },
    { 'S0049': 'I made fun of Toms accent.' },
    { 'S0050': 'Tom speaks with a French accent.' },
    { 'S0051': 'Is this price acceptable?' },
    { 'S0052': 'Thats just not acceptable.' },
    { 'S0053': 'It happened by accident.' },
    { 'S0054': 'I just had an accident.' },
    { 'S0055': 'It was all an accident.' },
    { 'S0056': 'It was just an accident.' },
    { 'S0057': 'Tom was in an accident.' },
    { 'S0058': 'I played the accordion.' },
    { 'S0059': 'Tom has a Swiss bank account.' },
    { 'S0060': 'I want to close the account.' },
    { 'S0061': 'Dont you have an accountant?' },
    { 'S0062': 'Why dont we get acquainted?' },
    { 'S0063': 'He is a man of action.' },
    { 'S0064': 'Tom is a man of action.' },
    { 'S0065': 'Now is the time for action.' },
    { 'S0066': 'Whos your favorite actor?' },
    { 'S0067': 'Im not much of an actor.' },
    { 'S0068': 'I want to be an actor.' },
    { 'S0069': 'Tom had nothing more to add.' },
    { 'S0070': 'Please take me to this address.' },
    { 'S0071': 'Dont let him know her address.' },
    { 'S0072': 'Can you tell me your address?' },
    { 'S0073': 'Would you give me Toms address?' },
    { 'S0074': 'Tom forgot Marys address.' },
    { 'S0075': 'I gave Tom a fake address.' },
    { 'S0076': 'Do you know Toms home address?' },
    { 'S0077': 'How did you get my address?' },
    { 'S0078': 'Tell me Toms email address.' },
    { 'S0079': 'Let me give you my address.' },
    { 'S0080': 'Can you give me Toms address?' },
    { 'S0081': 'This is my email address.' },
    { 'S0082': 'This is my business address.' },
    { 'S0083': 'When did you change your address?' },
    { 'S0084': 'Tom deserves admiration.' },
    { 'S0085': 'Tom wants to be admired.' },
    { 'S0086': 'How much is the admission?' },
    { 'S0087': 'Tom said he was adopted.' },
    { 'S0088': 'Arent they adorable?' },
    { 'S0089': 'Isnt that adorable?' },
    { 'S0090': 'Tom is just adorable.' },
    { 'S0091': 'Can you pay me in advance?' },
    { 'S0092': 'We do have one advantage.' },
    { 'S0093': 'We may have one advantage.' },
    { 'S0094': 'Im looking for adventure.' },
    { 'S0095': 'I will act on your advice.' },
    { 'S0096': 'I turned to him for advice.' },
    { 'S0097': 'Why dont we ask Toms advice?' },
    { 'S0098': 'Tom ignored Marys advice.' },
    { 'S0099': 'Tom asked Mary for advice.' },
    { 'S0100': 'Tom should take Marys advice.' }
  ]
}
